server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios_db
    username: root
    password: P455W0rD.f0r.My5QL
logging:
  level:
    org:
      springframework:
        security: DEBUG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup User"
appVersion: "1.0.0"
